print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weight?", end=' ')
weight = input()

print(f"So, you're {age} old, {height} tall and {weight} heavy.")
hobby = input("What is your hobby: ")
eat = input("What is your favorite food: ")
print(f"So, you like {hobby} and eat {eat})))")
